# Welcome to Jekyll 
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


show_downloads: true
theme: jekyll-theme-minimal
repository: inslichtruecken/gpx


# custom properties for this GPX Site
title: Frisch Luft Wege
logo: /assets/img/inslichtruecken.png
description: Manage and present your GPX Tracks
impressum: https://www.frischluftwege.de/impressum/
gdpr-notice: https://help.github.com/en/github/site-policy/github-privacy-statement/
legal: https://www.frischluftwege.de/rechtliche-hinweise/
mylink: https://www.frischluftwege.de/"
seo-keywords: gps, navigation, outdoor, hiking



collections:
  tracks:
    output: true
    permalink: /:collection/:title
    sequence: 2
  
 
    
    
   
